<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>sjs</string>
	</array>
	<key>name</key>
	<string>ServerSide Javascript</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.js</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.serverside-js</string>
	<key>uuid</key>
	<string>823c3add-1f1e-45cd-a299-dfa1f36f9d5e</string>
</dict>
</plist>
